name: TestPlugin
version: '${project.version}'
main: me.shadow_warrior.testplugin.TestPlugin
api-version: 1.17
authors: [ shadow_warrior_ ]
description: Particles and stuff
commands:
  tot435236:
    description: totem